### ISSUE TITLE
Linker fails on Linux

### ISSUE THREAD

**Issue by ojensen5115** [emilk/wfc#5]
The linking stage fails on Linux (`Linux eenie 4.6.0-1-amd64 #1 SMP Debian 4.6.4-1 (2016-07-18) x86_64 GNU/Linux`) with the following error:

`/usr/bin/ld: build/main.o: undefined reference to symbol 'floor@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libm.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status`

Adding `-lm` to the linker command line solves the issue for me.

**Comment by emilk** [comment]
Thanks for the report - before it I pushed my own fix for Ubuntu 16.04. Please try it and see if it resolves if for you too!

**Comment by ojensen5115** [comment]
It does, thank you!
